<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.2.0" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
		<PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
		
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.10" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.70.0" />
		<PackageReference Include="NLog" Version="6.1.1" />
		<PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Securebydesign.Application\Securebydesign.Application.csproj" />
		<ProjectReference Include="..\Securebydesign.Infrastructure\Securebydesign.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Hubs\" />
	</ItemGroup>

</Project>